[package]
name = "fnvm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blc = "0.6.0"
rand = "0.8.4"
lambda_calculus = "^2.0"
hex-slice = "0.1.4"